book/urls.py
from django.urls import path
from . import views


# app_name='book'
urlpatterns = [
    path('book', views.BookView.as_view(), name='book_list'),
    path('book_detail/<int:id>/', views.BookDetailView.as_view()),
    path('book_list/<int:id>/delete/', views.BookDropView.as_view()),
    path('book_list/<int:id>/update/', views.UpdateBookPostView.as_view()),
    path('create_post_book/', views.CreateBookPostView.as_view()),
    path('add-cooment/', views.createBookView),
    path('search/', views.SearchView.as_view(), name='search'),
]

custom_users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view()),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('logout/', views.AuthLogoutView.as_view(), name='logout'),
    path('user_list/', views.PostView.as_view(), name='post'),
]

main/urls.py
# from django.contrib import admin
# from django.urls import path
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
    path('', include('custom_users.urls')),
    path('', include('cloth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Авторизация</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Войти</button>
</form>
<a href="/register/">У вас нет аккаунта?</a>
</body>
</html>

templates/users/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Ура вы успешно прошли FaceControl</h1>
<p>Списки приглашенных</p>
<ol>
    {% for i in object_list %}
    <li>
        <h2>{{i.username}}</h2>
    </li>
    {% endfor %}
</ol>
<form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
    <button type="submit">Выйти из аккаунта</button>
</form>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Регистрация</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Регистрация</button>
</form>
</body>
</html>